### ISSUE TITLE
L2 Specs for Baseline Protocol

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#35]

**Comment by jack-garvin** [comment]
Assign to me, please.  I have a team ready to tackle this one.

**Comment by Therecanbeonlyone1969** [comment]
@Consianimis @jack-garvin ... anything scaling-related needs to be put in the right bucket this is not a standalone bucket but is spread across several areas - account management, VSM, onchain verification, workflow interoperability etc. ... I am going to add the collection of current requirements that are L2 related here but they need to be put into the right buckets otherwise we reference implementations in a spec and that is a no-no

**Comment by jack-garvin** [comment]
So glad to see you pointing out the no-no regarding reference implementations! I've been thinking the same thing for weeks. 

Most of the current standards docs rely on a specific use-case for ease of understanding - supply chain. We have to keep implementation specifics out of the standards docs. However, we can use specifics if presented as an implementation example. 

Let's get those L2 requirements posted!

**Comment by Therecanbeonlyone1969** [comment]
@jack-garvin here is the list of L2 requirements as of now: https://github.com/ethereum-oasis/baseline-roadmap/issues/174

**Comment by Consianimis** [comment]
@jack-garvin  -  I have assigned to you.
