### ISSUE TITLE
Messaging Specification Addition Request

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-standard#48]
Currently the specification on messaging contemplates the use of a messaging service such as NATS, AMQP or Kafka (etc).  It should be considered whether and how the message payload of a baselined workstep may be transmitted to the receiver(s) via email or other such message service.  What are the restrictions that should be applied, if any, to such use that would not apply in the case of NATS, AMQP or the others?  Would there be a condition that would make the use of email grounds for considering an otherwise properly-implemented baselined system non-compliant?

**Comment by kthomas** [comment]
IMHO, this is destined to be a disaster unless you are attaching machine-readable files and sending the emails in an automated way. You could implement an email provider which conforms to the `IMessagingService` interface and it would work as of v0.1.0.

I know you are asking about how restrictions could make such an interface be considered compliant. There are already restrictions though on email itself... attachment size limit comes to mind... so you are already going to need other tools to really "baseline" anything that was received via email.

Why not just connect to a baseline stack?

**Comment by Therecanbeonlyone1969** [comment]
@humbitious ... standards texts would usually specify  the abstract but still measurable requirement, for example, "A proposed commercial state MUST be based on a commercial document, more generally a state object, that modifies the commercial state between Buyer and Seller." "A proposed commercial state MUST be recorded on a DLT" -> "The Buyer MUST notify the Seller of a new proposed commercial state caused by a commercial state transition by the Buyer." -> "A proposed commercial state MUST be agreed to by Buyer and Seller before it is finalized." -> "A finalized commercial state MUST be recorded on a DLT" and finally "An agreement between Buyer and Seller MUST be non-repudiable." ... I hope this makes sense. This allows for great flexibility in how an implementation for example can deliver the proposed commercial state change as a PDF with a QR code that contains an endpoint that prompts the Buyer to sign the document, for example via docusign, which in turn calls the baseline stack and records everything as a zkp proof onchain.

cc @kthomas

**Comment by mehranshakeri** [comment]
This is another good example where I get confused between different boundaries of the protocol specification.

A Baseline instance has at least three communication boundaries/types.

1. Communication from the applications consuming Baseline which are usually under the same ownership. e.g. Company A running an ERP system connected to its own Baseline instance. Let's call it **INTERNAL** communication.
2. Communication between Baseline instance and the ledger as the common reference frame, e.g. for ZKP proof submissions. Let's call it **PUBLIC** communication.
3. Communication between different Baseline instances owned by different entities who are involved in a common business process. Let's call this **PARTNER** communication.

Does the Baseline Protocol's intention is to address all the boundaries or not is a question for itself.

- `IMessagingService` interface as described in the [documentation](https://docs.baseline-protocol.org/baseline-protocol/packages/messaging#interfaces) sounds _internal_. Interface can be part of the protocol but any implementation will be out of scope. Incompatible interface will break _internal_ communication but not necessarily _partner_ or _public_ one.
- Minimum data model and how to interpret a message MUST be part the protocol but distinguished and (most probably) different per communication boundaries. Incompatibility will break all the communication boundaries.
- How to detect and use a communication channel, let it be EMAIL or not, will be another part of the protocol which is a MUST for _partner_ and _public_ communication but not necessarily for _internal_. The reason is, a _partner_ or _public_ communication is always cross different instances (different ownership) but an _internal_ communication could be inside a single owned stack and one can decide if internally they want to stay Baseline compliant or not.
